name: Create Folder
on:
  organization_invitation:
    types: [created]
jobs:
  create-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Create Student Folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/$ORG_INVITE_USERNAME
          cp -r $GITHUB_WORKSPACE/.github/template/. $GITHUB_WORKSPACE/$ORG_INVITE_USERNAME
        env:
          ORG_INVITE_USERNAME: ${{ github.event.invitation.login }}
