name: Create Folder

on:
  membership:
    types: [added]

jobs:
  create-folder:
    runs-on: ubuntu-latest
    steps:
    - name: Create Student Folder
      run: |
        mkdir $GITHUB_WORKSPACE/$MEMBER_LOGIN
        cp -r $GITHUB_WORKSPACE/template/. $GITHUB_WORKSPACE/$MEMBER_LOGIN
      env:
        MEMBER_LOGIN: ${{ github.event.membership.user.login }}
